### ISSUE TITLE
Support for custom journal table name

### ISSUE THREAD

**Issue by danehnert** [drwatson1/dbup-cli#11]
It would be nice to have the option to change the schema and table name of the journal table. I saw that there is a journal class in your code, however adding the following lines to my .yml file causes a serialization exception:

```yaml
  journalTo:
    schema: dbo
    table: Migration 
```
